services:
  app:
    build: .
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=ComputerGames;User Id=sa;Password=Your_Password123;TrustServerCertificate=True
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_Password123
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:

