// <auto-generated />
using ComputerGamesORM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerGamesORM.Data.Migrations
{
    [DbContext(typeof(ComputerGamesContext))]
    partial class ComputerGamesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComputerGamesORM.Data.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Games_Name");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("ComputerGamesORM.Data.Models.GameDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasDatabaseName("IX_GameDescriptions_GameId");

                    b.ToTable("GameDescriptions", (string)null);
                });

            modelBuilder.Entity("ComputerGamesORM.Data.Models.GameDescription", b =>
                {
                    b.HasOne("ComputerGamesORM.Data.Models.Game", "Game")
                        .WithOne("GameDescription")
                        .HasForeignKey("ComputerGamesORM.Data.Models.GameDescription", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ComputerGamesORM.Data.Models.Game", b =>
                {
                    b.Navigation("GameDescription");
                });
#pragma warning restore 612, 618
        }
    }
}
